#!/usr/bin/bash

if [ "$1" = "env" ]; then
  bash `dirname $0`/18c_env.sh
elif [ "$1" = "sw" ]; then
  bash `dirname $0`/18c_linux_x64.sh
elif [ "$1" = "db" ]; then
  command bash `dirname $0`/18c_linux_x64.sh && command bash `dirname $0`/18c_netca.sh && command bash `dirname $0`/18c_dbca.sh || exit
elif [ "$1" = "apex" ]; then
  bash `dirname $0`/19c_apex.sh
elif [ "$1" = "all" ]; then
  command bash `dirname $0`/18c_linux_x64.sh && command bash `dirname $0`/18c_netca.sh && command bash `dirname $0`/18c_dbca.sh && command bash `dirname $0`/19c_apex.sh || exit
elif [ "$1" = "poc" ]; then
  command bash `dirname $0`/18c_linux_x64.sh && command bash `dirname $0`/18c_netca.sh && command bash `dirname $0`/18c_dbca.sh && command bash `dirname $0`/19c_apex.sh && command bash `dirname $0`/19c_apex_xdb.sh || exit
elif [ "$1" = "clean" ]; then
  command bash `dirname $0`/18c_linux_x64_clean.sh || exit
else
  echo "setup 1.02"
  echo "Usage: setup [env|sw|db|apex|all|clean]"
  echo "  env     Collect user inputs and create env file"
  echo "  sw      Install Oracle 18c softwrae only"
  echo "  db      Install Oracle 18c, configure Oracle Listener and create container and pluggable databases"
  echo "  apex    Create Oracle tablespace and install apex 19c"
  echo "  all     Perform sw, db and apex with ords.war built"
  echo "  poc     Perform sw, db and apex with xdb http"
  echo "  clean   Delete Oracle 18c, account, groups"
  exit 2
fi

